name: 'Suyu Docker Image CI'
on:
  #  workflow_dispatch:
  #  inputs: {}
    #  schedule:
    #    - cron: '0 7 * * 0'
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # image: ["linux-clang-format", "linux-fresh", "linux-mingw", "linux-transifex"]
        image: ["linux-clang-format", "linux-fresh", "linux-mingw"]
    
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      name: Setup Docker BuildX system
    - name: Login to the Suyu Package Registry
      uses: docker/login-action@v1
      if: (github.ref == 'refs/heads/dev') && (github.repository == 'suyu/build-environments')
      with:
        registry: git.suyu.dev
        username: ${{ secrets.FORGEJO_USERNAME }}
        password: ${{ secrets.FORGEJO_TOKEN }}
    - uses: docker/build-push-action@v2
      name: Build image
      with:
        push: ${{ (github.ref == 'refs/heads/dev') && (github.repository == 'suyu/build-environments') }}
        context: ${{ matrix.image }}
        tags: suyu/build-environments:${{ matrix.image }}
