name: 'Suyu Docker Image CI'

on:
  # workflow_dispatch:
  #   inputs: {}
  schedule:
    - cron: '0 7 * * 0'
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: docker-build
    strategy:
      matrix:
        # image: ["linux-clang-format", "linux-fresh", "linux-mingw", "linux-transifex"]
        image: ["forgejo-runner-dind", "linux-clang-format", "linux-fresh", "linux-mingw"]
    
    steps:
    - uses: https://github.com/actions/checkout@v2
    - uses: https://github.com/docker/setup-buildx-action@v1
      name: Setup Docker BuildX system
    - name: Login to Docker Container Registry
      uses: https://github.com/docker/login-action@v1
      if: (github.ref == 'refs/heads/dev') && (github.repository == 'suyu/build-environments')
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
    - uses: https://github.com/docker/build-push-action@v2
      name: Build images
      with:
        push: ${{ (github.ref == 'refs/heads/dev') && (github.repository == 'suyu/build-environments') }}
        context: ${{ matrix.image }}
        tags: fijxu/build-environments:${{ matrix.image }}
